#!/bin/bash
#echo $(pwd)
# params
# $1 = chapter 1 -> 5
# $2 = question number
c=$1
q=$2
if [ $1 == 1 ]
then
	qfile=./source/chapter_1_answer_key.txt
	qmax=293
fi
if [ $1 == 2 ]
then
	qfile=./source/chapter_2_answer_key.txt
	qmax=192
fi
if [ $1 == 3 ]
then
	qfile=./source/chapter_3_answer_key.txt
	qmax=160
fi
if [ $1 == 4 ]
then
	qfile=./source/chapter_4_answer_key.txt
	qmax=200
fi
if [ $1 == 5 ]
then
	qfile=./source/chapter_5_answer_key.txt
	qmax=220
fi

question_file="$c.$q" 
echo "" >> ./questions/$question_file
echo "{AS}" >> ./questions/$question_file
		result_line=$(grep -w "$q" $qfile)
		#echo "[debug][chapter: $c question: $q] get_q_a, result_line: $result_line"
		echo "$result_line" >> ./questions/$question_file
echo "{AE}" >> ./questions/$question_file
